---
title: "Team 4k1e_rda"
sidebar: false 
code-fold: true
---

This is our project webpage.

Please stay tuned to learn the effects of education and gender on crime tendencies.

# Team Members

1.  [Serra Özkan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-serraozkan-ini/)

2.  [Rabia Fışkın](https://emu-hacettepe-analytics.github.io/emu430-fall2023-DevFiskin/)

3.  [Nur Göv](https://emu-hacettepe-analytics.github.io/emu430-fall2023-nurgov/)

4.  [Selenay Sarıkaya](https://emu-hacettepe-analytics.github.io/emu430-fall2023-selenaysrky/)

5.  [Anıl Solakoğlu](https://emu-hacettepe-analytics.github.io/emu430-fall2023-AnilSolakoglu/)

6.  [Bilge Kavaklı](https://emu-hacettepe-analytics.github.io/emu430-fall2023-bilgekavakli/)

# Project Topic

The project covers the examination of various types of crimes between 2011 and 2020, taking into account the gender and educational status of the criminals. The data is taken from the Turkish Statistical Institute.

# Data Set

Our [Data Set **(click to access)**](data/suc%20turu%20ve%20egitim%20durumuna%20gore%20ceza%20infaz%20kurumuna%20giren%20hukumluler.xls) consists of crimes committed by criminals who have been judged by the [Turkish Penalty and Execution Institution](https://data.tuik.gov.tr/Bulten/Index?p=Ceza-Infaz-Kurumu-Istatistikleri-2020-37202). The number of crimes committed are categorized by years (2011-2020), types of crimes, gender of the criminal and their education status.

# Key Takeaways

-   The project focuses on understanding the dynamics of crime rates in Turkey from 2011 to 2020. It examines the relationships between crime rates, gender and education levels of offenders to gain insights into the demographic characteristics of criminals.

-   The primary dataset is obtained from "suc turu ve egitim durumuna gore ceza infaz kurumuna giren hukumluler.xls" from TÜİK, which contains information on people who have been sent to prison. In addition, index data from 2011 to 2020 are used to categorise and analyse crime trends. The dataset is processed using R with packages such as readxl, tidyr and dplyr.

-   The project focuses on the analysis of specific crime categories, including theft, murder and rape, to identify trends in different types of crime over the years. An important aspect of this analysis is to consider the gender and educational level of the criminals in order to identify patterns and correlations between these demographic characteristics and crime rates. The R code provided illustrates the detailed steps taken to process the data, including tasks such as cleaning, structuring, handling NAs and preparing the data for visualisation.

-   The analysis produces some interesting results, particularly when looking at crime trends over the period 2011-2020. The plotted data reveals different patterns of crime rates in different categories, with some showing fluctuations and others showing rapid changes, possibly influenced by legal changes or social dynamics. Gender analysis adds depth to the findings, revealing which crimes are more common among certain genders and how these patterns evolve over the years. The use of logarithmic scaling on the y-axis strengthens the visualisation, allowing for the different magnitudes of crime rates and facilitating a more nuanced understanding of the data.

-   The project aims to contribute to the development of effective crime control policies by providing a detailed understanding of crime dynamics in Turkey. The resulting analyses, including crime trends, gender patterns and correlations with education levels, can inform policy makers and law enforcement agencies. The project output is saved as 'crime_numbers.RData' for future reference and analysis. The comprehensive analysis undertaken in this project provides valuable insights that can guide efforts to create a safer society and formulate targeted crime prevention and law enforcement strategies.

